apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oracle-rdbms-oradata
  namespace: oracle-namespace
  labels:
    app: oracle-rdbms
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: oracle-rdbms-config
  namespace: oracle-namespace
  labels:
    app: oracle-rdbms
data:
  ORACLE_BASE: "/opt/oracle"
  ORACLE_HOME: "/opt/oracle/product/19c/dbhome_1"
  ORACLE_CHARACTERSET: "AL32UTF8"
  ORACLE_EDITION: "enterprise"
  ORACLE_SID: "ORCLSID"
  ORACLE_PDB: "ORCLPDB"
  ORACLE_PWD: "orclpwd"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oracle-rdbms
  labels:
    app: oracle-rdbms
  namespace: oracle-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oracle-rdbms
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: oracle-rdbms
    spec:
      containers:
        - name: rdbms
          image: localhost:32000/oracledb:19.3.0-ee
          env:
            - name: ORACLE_SID
              valueFrom:
                configMapKeyRef:
                  name: oracle-rdbms-config
                  key: ORACLE_SID
            - name: ORACLE_PDB
              valueFrom:
                configMapKeyRef:
                  name: oracle-rdbms-config
                  key: ORACLE_PDB
            - name: ORACLE_PWD
              valueFrom:
                configMapKeyRef:
                  name: oracle-rdbms-config
                  key: ORACLE_PWD
            - name: ORACLE_CHARACTERSET
              valueFrom:
                configMapKeyRef:
                  name: oracle-rdbms-config
                  key: ORACLE_CHARACTERSET
            - name: ORACLE_EDITION
              valueFrom:
                configMapKeyRef:
                  name: oracle-rdbms-config
                  key: ORACLE_EDITION
          ports:
            - containerPort: 1521
              name: oracle-listener
            - containerPort: 5500
              name: oem-express
          volumeMounts:
          - name: oradata
            mountPath: /opt/oracle/oradata
      volumes:
        - name: oradata
          persistentVolumeClaim:
            claimName: oracle-rdbms-oradata
---
apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: oracle-namespace
  labels:
    app: oracle-rdbms
spec:
  ports:
    - name: listener
      port: 1521
      targetPort: oracle-listener
  selector:
    app: oracle-rdbms