CREATE TABLE RESTAURANTS_OWNER.ITEMS (
    ITEM_ID NUMBER(5, 0) DEFAULT RESTAURANTS_OWNER.ITEM_ID_GENERATOR.NEXTVAL,
    ITEM_NAME VARCHAR2(30) NOT NULL,
    PRICE FLOAT(53) NOT NULL,
    RESTAURANT_ID NUMBER(5, 0),
    LINE_ID NUMBER(5, 0),
    CONSTRAINT ITEM_PK PRIMARY KEY (ITEM_ID),
    CONSTRAINT ITEM_REST_FK FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANTS_OWNER.RESTAURANTS (RESTAURANT_ID)
);