CREATE SEQUENCE RESTAURANTS_OWNER.RESTAURANT_ID_GENERATOR START WITH 1;
CREATE SEQUENCE RESTAURANTS_OWNER.ITEM_ID_GENERATOR START WITH 1;
CREATE SEQUENCE RESTAURANTS_OWNER.LINE_ID_GENERATOR START WITH 1;