CREATE SEQUENCE ORDERS_OWNER.USER_ID_GENERATOR START WITH 1;
CREATE SEQUENCE ORDERS_OWNER.TOKEN_ID_GENERATOR START WITH 1;
CREATE SEQUENCE ORDERS_OWNER.LINE_ITEMS_ID_GENERATOR START WITH 1;
CREATE SEQUENCE ORDERS_OWNER.ORDER_ID_GENERATOR START WITH 1;
