CREATE TABLE ORDERS_OWNER.ITEMS (
    ITEM_ID NUMBER(5, 0),
    ITEM_NAME VARCHAR2(50) NOT NULL,
    PRICE FLOAT(53) NOT NULL,
    RESTAURANT_ID NUMBER(5, 0),
    CONSTRAINT ITEM_PK PRIMARY KEY (ITEM_ID),
    CONSTRAINT ITEM_FK FOREIGN KEY (RESTAURANT_ID) REFERENCES ORDERS_OWNER.RESTAURANTS (RESTAURANT_ID)
);