CREATE TABLE ORDERS_OWNER.TOKENS (
    TOKEN_ID NUMBER(5, 0) DEFAULT ORDERS_OWNER.TOKEN_ID_GENERATOR.NEXTVAL,
    TOKEN_VALUE VARCHAR2(100) NOT NULL,
    TOKEN_TYPE VARCHAR2(10) NOT NULL,
    REVOKED CHAR(1) DEFAULT 'N' NOT NULL,
    EXPIRED CHAR(1) DEFAULT 'N' NOT NULL,
    USER_ID NUMBER(5, 0),
    CONSTRAINT TOKEN_PK PRIMARY KEY (TOKEN_ID),
    CONSTRAINT USER_ID_FK FOREIGN KEY (USER_ID) REFERENCES ORDERS_OWNER.USERS (USER_ID),
    CONSTRAINT REVOKED_CHECK CHECK (REVOKED IN ('Y', 'N')),
    CONSTRAINT EXP_CHECK CHECK (EXPIRED IN ('Y', 'N'))
);