CREATE TABLE DELIVERIES_OWNER.COURIERS (
    COURIER_ID NUMBER(5, 0) DEFAULT DELIVERIES_OWNER.COURIER_ID_GENERATOR.NEXTVAL,
    PAYMENT_INFO VARCHAR2(30),
    COURIER_STATUS VARCHAR2(10) NOT NULL,
    CONSTRAINT COURIES_PK PRIMARY KEY (COURIER_ID)
);