CREATE TABLE PAYMENTS_OWNER.TRANSACTIONS (
    TRANSACTION_ID VARCHAR2(100),
    SENDER_ID VARCHAR2(50) NOT NULL,
    RECEIVER_ID VARCHAR2(50) NOT NULL,
    AMOUNT FLOAT(53) NOT NULL,
    CORRELATION_ID VARCHAR2(100) NOT NULL,
    ISSUED_AT DATE NOT NULL,
    RESULT VARCHAR2(15) NOT NULL,
    CONSTRAINT TRANSACTION_PK PRIMARY KEY (TRANSACTION_ID),
    CONSTRAINT TRANSACTION_SENDER_FK FOREIGN KEY (SENDER_ID) REFERENCES PAYMENTS_OWNER.PARTICIPANTS (PARTICIPANT_ID),
    CONSTRAINT TRANSACTION_RECEIVER_FK FOREIGN KEY (RECEIVER_ID) REFERENCES PAYMENTS_OWNER.PARTICIPANTS (PARTICIPANT_ID)
);