GRANT CREATE SESSION TO ORDERS_OWNER;
GRANT CREATE SESSION TO RESTAURANTS_OWNER;
GRANT CREATE SESSION TO PAYMENTS_OWNER;
GRANT CREATE SESSION TO DELIVERIES_OWNER;

GRANT UNLIMITED TABLESPACE TO ORDERS_OWNER;
GRANT UNLIMITED TABLESPACE TO RESTAURANTS_OWNER;
GRANT UNLIMITED TABLESPACE TO PAYMENTS_OWNER;
GRANT UNLIMITED TABLESPACE TO DELIVERIES_OWNER;