apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: kafka
  labels:
    name: kafka
spec:
  ports:
    - port: 9092
      targetPort: 9092
      name: kafka-port
      protocol: TCP
  selector:
    app: kafka
    id: "0"
  type: ClusterIP
---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: kafka
  name: kafka-broker0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
      id: "0"
  template:
    metadata:
      labels:
        app: kafka
        id: "0"
    spec:
      containers:
        - name: kafka
          image: wurstmeister/kafka
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_ADVERTISED_PORT
              value: "9092"
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: 10.152.183.59
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: 10.152.183.18:2181
            - name: KAFKA_BROKER_ID
              value: "0"