apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonatypestorage
  namespace: nexus
  labels:
    name: sonatypestorage
spec:
  storageClassName: microk8s-hostpath
  capacity:
    storage: 40Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  hostPath:
    path: /home/thaimore/kuber-images
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonatype-registry-data
  namespace: nexus
spec:
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: sonatype-service
  namespace: nexus
spec:
  ports:
    - name: sonatype-registry
      port: 32145
      protocol: TCP
      targetPort: 8081
  selector:
    app: sonatype-registry
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonatype-registry
  namespace: nexus
  labels:
    app: sonatype-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonatype-registry
  template:
    metadata:
      labels:
        app: sonatype-registry
    spec:
      volumes:
        - name: registry-vol
          persistentVolumeClaim:
            claimName: sonatype-registry-data
      containers:
        - image: sonatype/nexus3
          name: nexus3
          resources:
            limits:
              memory: "4Gi"
              cpu: "1000m"
            requests:
              memory: "2Gi"
              cpu: "500m"
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: registry-vol
              mountPath: /nexus-data
              subPath: sonatype